name: Build and push to DockerHub
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        name: app
        path: app/build/libs
    - name: Build & Push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: jorgesotoaudelo/ai_presentation_generator
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
